### ISSUE TITLE
`dacite.exceptions.WrongTypeError` raised when a `bool` property is defined in `ConfigModel`

### ISSUE THREAD

**Issue by nullqwertyuiop** [GraiaProject/kayaku#4]
**Describe the bug**
`dacite.exceptions.WrongTypeError` raised when a `bool` property is defined in `ConfigModel`
```text
Traceback (most recent call last):
  File "...\test.py", line 13, in <module>
    kayaku.create(TestConfig)
  File "...py3.10\lib\site-packages\kayaku\model.py", line 136, in create
    model_store.instance = from_dict(cls, container)
  File "...py3.10\lib\site-packages\dacite\core.py", line 68, in from_dict
    raise WrongTypeError(field_path=field.name, field_type=field.type, value=value)
dacite.exceptions.WrongTypeError: wrong value type for field "test_value" - should be "bool" instead of value "JWrapper(<kayaku.backend.types.JWrapper object at 0x000001F646D4B070>, value=True, __orig_class__=kayaku.backend.types.JWrapper[bool], json_before=[WhiteSpace(' ')], json_after=[])" of type "JWrapper"
```

**To Reproduce**
Code to reproduce the behavior:
```python
if __name__ == "__main__":
    import kayaku

    kayaku.initialize({"{**}": "./test/{**}"})


    @kayaku.config("test")
    class TestConfig:
        test_value: bool = True


    kayaku.create(TestConfig)

    kayaku.bootstrap()
    kayaku.save_all()
```
1. Run the code
2. See file `./test/test.jsonc` and `./test/test.schema.json` with the correct value
3. Run the code again
4. See the error

**Expected behavior**
`TestConfig` should be properly read from file.

**Enviroment**
```text
[tool.poetry.dependencies]
python = "^3.10"
kayaku = "0.5.0rc3"
```

**Additional Content**
Tested with more models, seems like only the one with `bool` property would raise this exception.
```python
if __name__ == "__main__":
    import kayaku

    kayaku.initialize({"{**}": "./test/{**}"})


    @kayaku.config("test.str")
    class TestStrConfig:
        test_value: str = "test"


    @kayaku.config("test.int")
    class TestIntConfig:
        test_value: int = 0


    @kayaku.config("test.bool")
    class TestBoolConfig:
        test_value: bool = True


    kayaku.create(TestStrConfig)
    kayaku.create(TestIntConfig)
    kayaku.create(TestBoolConfig)

    kayaku.bootstrap()
    kayaku.save_all()
```

**Comment by GreyElaina** [comment]
Fixed in 0.5.0rc3
